project:
  type: book
  output-dir: _book

# Book formatting types and options
format:
  html:
    theme: 
      - cosmo
      - r4epi_styles.scss
  pdf:
    documentclass: scrreprt
    
  
    
# Bibliography and citation options
bibliography: references.bib
csl: ama.csl

# Set editor to default to source view instead of visual view
editor: source

# To make sure that R, Python, and Julia code is only executed locally, 
# configure your project to use Quarto’s freeze feature by adding this to your 
# _quarto.yml. (https://quarto.org/docs/publishing/netlify.html)
execute:
  freeze: auto

# Book structure and options
book:
  # Basic metadata
  title: "R 4 Epidemiology"
  date: today
  favicon: r4epi_favicon.png
  site-url: https://brad-cannell.github.io/r4epi_quarto/
  repo-url: https://github.com/brad-cannell/r4epi_quarto
  repo-actions: [edit, issue]
  page-footer: 
    left: |
      R for Epidemiology
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  # Book options
  search: true
  downloads: [pdf] # https://quarto.org/docs/books/book-output.html#sidebar-tools
  sharing: [twitter, facebook, linkedin]
  page-navigation: true # Haven't played with this much yet. https://quarto.org/docs/books/book-structure.html#page-navigation

  # Chapter sturcture
  # https://quarto.org/docs/books/book-structure.html
  chapters:
    # Index is the landing page for the HTML version of the book.
    - index.qmd
    - chapters/introduction.qmd
    - chapters/contributing/contributing.qmd
    - chapters/about_the_authors/about_the_authors.qmd
    
    # Parts can be qmd files (if you want explanitory text) or characater strings
    # if you only want a part title. The separate qmd document method does not 
    # look good in pdf format.
    - part: "Getting Started"
      chapters: 
        - chapters/installing_r_and_rstudio/installing_r_and_rstudio.qmd
        - chapters/what_is_r/what_is_r.qmd
        - chapters/navigating_rstudio/navigating_rstudio.qmd
        - chapters/speaking_r/speaking_r.qmd
        - chapters/lets_get_programming/lets_get_programming.qmd
        - chapters/asking_questions/asking_questions.qmd
      
    - part: "Coding Tools and Best Practices"
      chapters:
        - chapters/r_scripts/r_scripts.qmd
        - chapters/quarto_files/quarto_files.qmd
        - chapters/r_projects/projects.qmd
        - chapters/best_practices/best_practices.qmd
        - chapters/using_pipes/using_pipes.qmd
        
    - part: "Data Transfer"
      chapters: 
      - chapters/data_transfer/data_transfer.qmd
      - chapters/file_paths/file_paths.qmd
      - chapters/importing_plain_text/importing_plain_text.qmd
      - chapters/importing_binary_files/importing_binary_files.qmd
        
      
         
    - part: "Collaboration"
      chapters: 
      - chapters/intro_git_github/intro_git_github.qmd
      - chapters/using_git_github/using_git_github.qmd
      
    
    - part: "References"
      chapters:
        - references.qmd
  
  # We can also add appendices and track them separately from other book parts.  
  appendices:
    - chapters/appendices/glossary.qmd
